# Generated by Django 4.1.5 on 2023-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cost', models.IntegerField()),
                ('enc', models.IntegerField()),
                ('group', models.PositiveSmallIntegerField(choices=[('Ordinary', 'ordinary'), ('Two-handed', 'two-handed')], default='Ordinary')),
                ('damage', models.IntegerField()),
                ('short_range', models.IntegerField()),
                ('long_range', models.IntegerField()),
                ('reload_in_actions', models.IntegerField()),
                ('availability', models.CharField(max_length=20)),
            ],
        ),
    ]
