# Generated by Django 4.1.5 on 2023-01-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='group',
            field=models.CharField(choices=[('Ordinary', 'ordinary'), ('Two-handed', 'two-handed')], default='Ordinary', max_length=30),
        ),
    ]
