# Generated by Django 4.1.5 on 2023-01-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0006_alter_weapon_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeaponCategory',
        ),
    ]
