# Generated by Django 4.1.5 on 2023-01-11 22:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0009_weapon_is_melee_alter_weapon_qualities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='group',
            field=models.CharField(choices=[('Ordinary', 'Zwykła'), ('Two-handed', 'Dwuręczna'), ('Cavalry', 'Kawaleryjska'), ('Flail', 'Korbacz'), ('Parying', 'Parująca'), ('Fencing', 'Szermiercza')], default=('Ordinary', 'Zwykła'), max_length=30),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='qualities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('is_armour_pisercing', 'Przebijający zbroję'), ('is_balanced', 'Wyważony'), ('is_defensive', 'Parujący'), ('is_experimental', 'Eksperymentalny'), ('is_fast', 'Szybki'), ('is_impact', 'Druzgoczący'), ('is_precise', 'Precyzyjny'), ('is_pummeling', 'Ogłuszający'), ('is_shrapnel', 'Odłamkowy'), ('is_slow', 'Powolny'), ('is_snare', 'Unieruchamiający'), ('is_tiring', 'Ciężki'), ('is_unreliable', 'Zawodny')], max_length=170),
        ),
    ]
