# Generated by Django 4.1.5 on 2023-01-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0017_alter_weapon_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='availability',
            field=models.CharField(choices=[('-', '-'), ('przeciętna', 'przeciętna'), ('duża', 'duża'), ('mała', 'mała'), ('rzadka', 'rzadka'), ('sporadyczna', 'sporadyczna'), ('znikoma', 'znikoma')], default=('przeciętna', 'przeciętna'), max_length=20),
        ),
    ]
