# Generated by Django 4.1.5 on 2023-01-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0019_rename_cost_weapon_cost_gc_weapon_cost_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='cost_p',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='cost_s',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
