# Generated by Django 4.1.5 on 2023-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0020_alter_weapon_cost_p_alter_weapon_cost_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='group',
            field=models.CharField(choices=[('Zwykła', 'Zwykła'), ('Długi Łuk', 'Długi Łuk'), ('Dwuręczna', 'Dwuręczna'), ('Kawaleryjska', 'Kawaleryjska'), ('Korbacz', 'Korbacz'), ('Kusza', 'Kusza'), ('Mechaniczna', 'Mechaniczna'), ('Parująca', 'Parująca'), ('Proca', 'Proca'), ('Rzucana', 'Rzucana'), ('Szermiercza', 'Szermiercza'), ('Unieruchamiająca', 'Unieruchamiająca')], default=('Ordinary', 'Zwykła'), max_length=30),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='reload_in_actions',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=(0, 0), null=True),
        ),
    ]
