# Generated by Django 4.1.5 on 2023-01-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0021_alter_weapon_group_alter_weapon_reload_in_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_two_handed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='group',
            field=models.CharField(choices=[('Zwykła', 'Zwykła'), ('Długi Łuk', 'Długi Łuk'), ('Dwuręczna', 'Dwuręczna'), ('Kawaleryjska', 'Kawaleryjska'), ('Korbacz', 'Korbacz'), ('Kusza', 'Kusza'), ('Mechaniczna', 'Mechaniczna'), ('Palna', 'Palna'), ('Parująca', 'Parująca'), ('Proca', 'Proca'), ('Rzucana', 'Rzucana'), ('Szermiercza', 'Szermiercza'), ('Unieruchamiająca', 'Unieruchamiająca')], default=('Ordinary', 'Zwykła'), max_length=30),
        ),
    ]
