# Generated by Django 4.1.5 on 2023-01-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0022_weapon_is_two_handed_alter_weapon_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='reload_in_actions',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, null=True),
        ),
    ]
