# Generated by Django 4.1.5 on 2023-01-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0023_alter_weapon_reload_in_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
