# Generated by Django 4.1.5 on 2023-01-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0025_alter_weapon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_damage_strength_depend',
            field=models.BooleanField(default=True),
        ),
    ]
